# Generated by Django 4.2.8 on 2023-12-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='Form',
            new_name='form',
        ),
    ]
