# Generated by Django 4.2.8 on 2023-12-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.IntegerField(choices=[(1, 'selection'), (2, 'comment'), (3, 'Boolean'), (4, 'File')], default=1),
        ),
    ]
