# Generated by Django 4.2.8 on 2023-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_file_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='value',
            field=models.URLField(blank=True, null=True),
        ),
    ]
